[2024-12-12T17:17:00.335+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_pipeline.plot_temperature scheduled__2024-12-12T16:00:00+00:00 [queued]>
[2024-12-12T17:17:00.339+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_pipeline.plot_temperature scheduled__2024-12-12T16:00:00+00:00 [queued]>
[2024-12-12T17:17:00.340+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2024-12-12T17:17:00.346+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): plot_temperature> on 2024-12-12 16:00:00+00:00
[2024-12-12T17:17:00.351+0000] {standard_task_runner.py:57} INFO - Started process 1131 to run task
[2024-12-12T17:17:00.353+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_pipeline', 'plot_temperature', 'scheduled__2024-12-12T16:00:00+00:00', '--job-id', '555', '--raw', '--subdir', 'DAGS_FOLDER/dag_weather.py', '--cfg-path', '/tmp/tmpa6t7ek0p']
[2024-12-12T17:17:00.355+0000] {standard_task_runner.py:85} INFO - Job 555: Subtask plot_temperature
[2024-12-12T17:17:00.389+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_pipeline.plot_temperature scheduled__2024-12-12T16:00:00+00:00 [running]> on host d8e35828fd29
[2024-12-12T17:17:00.436+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_pipeline' AIRFLOW_CTX_TASK_ID='plot_temperature' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-12T16:00:00+00:00'
[2024-12-12T17:17:00.448+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2369, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "°C"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_weather.py", line 45, in plot_temperature
    df['temperature'] = pd.to_numeric(df['current_units_temperature_2m'])
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/tools/numeric.py", line 185, in to_numeric
    values, _ = lib.maybe_convert_numeric(
  File "pandas/_libs/lib.pyx", line 2411, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "°C" at position 0
[2024-12-12T17:17:00.454+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_pipeline, task_id=plot_temperature, execution_date=20241212T160000, start_date=20241212T171700, end_date=20241212T171700
[2024-12-12T17:17:00.461+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 555 for task plot_temperature (Unable to parse string "°C" at position 0; 1131)
[2024-12-12T17:17:00.492+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-12T17:17:00.504+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
